# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: afe166df02dd63b06233f53ac74bb4c4afc788a387fd624c70546959f3fd2b5534f8d786a67f8803530143f0cc9b47cae136027859d80900a2f9589557d56b47

test:
  secret_key_base: 1ce6e5d192ccb84a584ad692424ec80e70c77c6eacc2bb6a436032d6ba6f0f1c7c0a9a9ed30693397da5a7739d43574176086ae60366df4309f9a72534d4db12

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
